name: Actualizar Calendarios
on:
  schedule:
    - cron: "0 */6 * * *"   # Se ejecuta solo cada 6 horas
  workflow_dispatch: {}     # Esto permite que tú le des a un botón para actualizar cuando quieras

permissions:
  contents: write           # Permiso para que el robot pueda escribir los resultados en tu repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar herramientas
        run: pip install -r requirements.txt
        
      - name: Ejecutar el buscador de partidos
        run: python scraper.py
        
      - name: Guardar cambios automáticamente
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Actualización automática de partidos" || exit 0
          git push
